lamp_packages:
  - apache2
  - mariadb-server
  - php
  - php-mysql

apache:
  service:
    - apache2
    - mariadb
  user: www-data
  group: www-data

mariadb:
  python_lib: python3-pymysql
  socket: /var/run/mysqld/mysqld.sock
