lamp_packages:
  - httpd
  - mariadb-server
  - php
  - php-mysqlnd

apache:
  service:
    - httpd
    - mariadb
  user: apache
  group: apache

mariadb:
  python_lib: python3-PyMySQL
  socket: /var/lib/mysql/mysql.sock
