#SPDX-License-Identifier: MIT-0
---
# tasks file for lamp
- name: inclusion des vars
  include_vars: '{{ ansible_os_family }}.yml'

- name: installation lamp
  package:
    name: '{{ item }}'
    state: present
  loop: '{{ lamp_packages }}'

- name: démarrage services redhat
  when: ansible_os_family == 'RedHat'
  service:
    state: started
    name: '{{ item }}'
    enabled: true
  loop:
    - httpd
    - mariadb

- name: activation du mod_rewrite d'apache sur debian
  when: ansible_os_family == 'Debian'
  apache2_module:
    state: present
    name: rewrite
  notify:
    - restarting_apache

- name: mise en place de index.html
  template:
    src: index.j2
    dest: /var/www/html/index.html
    owner: '{{ apache.user }}'
    group: '{{ apache.group }}'
    mode: 0644
