---
- name: install dep
  package:
    name: '{{ mariadb.python_lib }}'
    state: present

- name: Créer une nouvelle db
  community.mysql.mysql_db:
    name: '{{ mariadb_user.name }}'
    state: present
    login_unix_socket: '{{ mariadb.socket }}'

- name: Create database user with name 'jeje' and password '1234567989' with all database privileges
  community.mysql.mysql_user:
    name: '{{ mariadb_user.name }}'
    password: '{{ mariadb_user.password }}'
    priv: '{{ mariadb_user.name }}.*:ALL'
    state: present
